version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    expose:
      - "3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
